### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s1-evaluacion-intermedia-carolcesp#1]
Good job @carolcesp.

Here you have some tips to improve it:

- [x] Menu options should be clickable
- [x] Page logo should be clickable too
- [x] In this case, our main navigation should be inside the `HEADER` tag
- [x] Where is our MAIN element? It would be great to wrap the main section around a `MAIN` tag
- [x] Block elements don't need to have their width set up to 100% nor 100vw
- [x] Remove extra black border
- [x] The header must have a fixed position

Once we have those fixed, we can finish the exercise details.

Let me know if you have any doubts ;)

**Comment by carolcesp** [comment]
I have added the correction in my branch > correction. Thanks
